language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: '#Na}^_Zgb7=q'
  bucket: programmingforprogress-frontend
  region: us-west-2
  secret_access_key:
    secure: aMZuT2kAYk67n7aiXbA0k0HNhBC5JOTBeqlrD/u19OU0dhsyvQoJQOahJsG048wrRYeK0vIIk0QURu9beYRbtSBERsa1kevACmqQ84CHI80MItA8eSZcV2fi0n/8XRWighuHVBRyvZWIk9BS07XIytM8x7MlUZs7jl9vcp9f9B/eUv6BqIXZG5pu+yHPjzzVYyVY/3NAdGezqiqeVb2Mn+wD1eFB5tWFiOhhRRcOcA/+I7QE6Y1q53qvl76eq3gihj+HcufKIkyozaKRaAIUrf9MYGWNwpOkZamoKFEbMdoD63uPPuBjBuLM0G00hdoeN/1pQy5B5q7g9oOjs2JFBlpZkz7ihbWnUvuR2velj8Rtg5hVkimn0Rwv9D+/6amQgQ1CbEh+yMWXfYOyn3sWBog4ym7RV+ZFZVms8BGopviuF3DHusHjEuu2d8sIElbIzu0/7ycja476Vqctw3uUf18NXZqWM5PySfnc8DXp58vgTxSBeBCRNqElDgT8FMLYNp6F/G9O8ciHG9vql2nr4D1FZSLPzsm4kQvB1Dn5p6Iutj4Ny0WvF8kgQs4+8W6LHMOFCwn1oEnGJwX6YggoWHefyPVkRddCVqCA2OIS1EYJezu2jxqYh0CxQb45zClEjb34WiwX7iqhdV90+2HZmLDpHANwQ3Ck8T3GNnjKOh0=
