language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: "#Na}^_Zgb7=q"
  bucket: programmingforprogress-frontend
  region: us-west-2
  secret_access_key:
    secure: h3ILFMaKQjrNYjgr2yzSnppSZl19Nf0R2cYEqLBqwNTP/p6GU7JnWr/X/+1jPfj/Z2iyS2zbQ3ttxZsA/h6XVxGQ8QtgD7KVCj7WCyWerVkIj3whQ9q66C7rlGp84r+oWNJQ6jWCTKwV0Oj/UEu5RUa51ux7eDCyx0j20ls5luXj6sEKjdnd04rZxs/shXOKX87W3X9gXAE7jCLYJhGEEq0r6uLC0dtR8X9AhKEIhNpopYoSEpNt69MeiUUS+go/SkieI3GccOjjPpfZFkBJzK/oLIAA1CU4q1V0wi2f2LRW9nul28JUXvNTY1McpbAKeNEwvehgLzsWgdhb5XjGU3FbaAYvH+LjMzoAQ3pfvwmvqgUtBv2uzb/NSR5YkEmzmLtUn2XEbwojXLq/zBEwMnH96llMVTP9VkI8PdD5Ie3ayCfv8Q2udDDJEdIGB/pt5jxxVLm340fQ3s3tsx4yiBTWclyanmlab+vf6JpIXcRUx9kmVRRhOrqjjdis4TuYW9odDCuUfXFk1KUcyUb1maSQKxTjaCGMllC3IFXE0Y+KT4fy8hMg3zlcpYz8kdG4vvjdt2BxjQhmFY6DRpsjDf0yHulPpNtf8DJQA4jRMPaBdJXvbVuYcED+GUqYWZ3f+CKfDO+MuB5BVTeCBQy05n2+8eqNYlsyUr/0YJDFwMM=
