language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: AKIAI7GVDYTTK5M7PLYA
  bucket: programmingforprogress-frontend
  region: us-west-2
  secret_access_key:
    secure: rCylzxQ5KUj3LZCNdw54oWbX2AsbAo8wn2yQiLAOdu17k2M46BpxXPev2R0U1X/8Jf8diaLqcx3wAZzbol25FVwZXn8W92+vybZaGtwOzp0Ii06ByAwfsDiz8LrrkKTaQYZHvUuu4ud4C9pWIeph/0tWtTvjWgNjkl+SWo9W4KJknzjOk+KXztpz3pQ8Cji4HfeDDbB9XfBLfsXB4oZSYM25hLnnYNESof7QbQTJZDdPcEPfdBI0ELTVLk3edo4cbPqTRLGHREx7vwGxLEAIhRLCaappsHhHNxgogVYGHJURnpUbatirIxqKN5Su/R8HGBnTbPBHa5IVrM8xalf2vGBvyeggUwWSZwbd3Ea10kFjc1wCZc6O/PEFjpS5cOCjF3hEN/ndVGOKrUQBYJoFZnaf0/6T0ETVOy005P4pYBMIpXPvyjGSvnDA/HYQGSsZMWCTlex8mUDA4GLO5Dx/4zIa5aP4/komJAAsn5S8UyRV4SlTKYINnaJE0CnFdoH+Nl3snQwp9Zw8N+7dDOe+lnoUqJt7uOkfXf2xBWp/T9KagiDrLSpuguG6GrdpkgEFI0ax4Baw23xQoHzdJLxAhpiKOlnaU6wdupH4OKI1nI6qzxrvlCmgGrxKv8qF1pi63JnRtIej8mLHqrPMoGDUy3+a8gHMvG0nyMTkVguT1bQ=
