language: node_js
node_js:
- '6.0'
before_install: npm install mocha
install: npm install
deploy:
  provider: s3
  access_key_id: "#Na}^_Zgb7=q"
  bucket: programmingforprogress-frontend
  region: us-west-2
  secret_access_key:
    secure: J0+iq6EK4FD51TXj7mkNnml91I8UyYhVX0lV3XmLauE3JXWjyY2AXLQ9DcNsp3WYgCohAFucHG0celDvLfB/zD59SF0g9maw6bRJlBYcngHp64zFErzx7AIgY+StWyLY7sdhMpuVnlL0XfjLR6VDR8wTqti5lYS2LOixS7ly31Fx1QrQ9K4RMQk3jesC0IA9zR0Uin7vDBzn8jZqRw5odYbElNfz3OBMU4rAcQ/Mt2BsRvpwUyewOJlm0YfeT7YZuKmcdi/LRk5QVWLC5EiTZSzO/0EwtfHUny70u6fGFXjRVhhmrPfNVrE+DNkEQXOXvFYj7L/RkIdYUlO3zeJ2vDl0OxSRQ47gu+eUcHbFWQCitUiYR/hr4oC4nmtkomLeOwZlW7+gIEkHtDmkbrLmc5qVi+P92ABjKiua05rHMe1MniSuBX57xYVkMz4VSkBUtGSG0ijkiek61zsTv9xGI9YbqqM5egiOQubpZBwVk/PqwiUYVyhD24feP8KXsb1UbYlNgjnFyHkjeLKJ/xETcybkZ25CZocIs+zhIZ19LomOOGk21NDnSLR5BY5HO3i/0aTjfdgsjl/vk2vDBlFgbCWw6CBoj+CkkcYuAXQW4vh2T9eKZPL9a2V7S8Mm66ex5PDMI4qO/8wrh4KN/ek2I94b8mUsDtuYZIuGGGuIXXw=
